automatic create or update second host only interface

diff --git a/boot2docker b/boot2docker
--- a/boot2docker
+++ b/boot2docker
@@ -12,7 +12,20 @@ VM_MEM=1024
 
 BOOT2DOCKER_ISO=./boot2docker.iso
 
+BOOT2DOCKER_HOST_IP=192.168.59.1
+BOOT2DOCKER_DHCP_IP=192.168.59.100
+BOOT2DOCKER_NetworkMask=255.255.255.0
+BOOT2DOCKER_lowerIPAddress=192.168.59.101
+BOOT2DOCKER_upperIPAddress=192.168.59.254
+BOOT2DOCKER_DHCP_Enabled=Yes
+
+
 test -f $HOME/.boot2docker/profile && . $HOME/.boot2docker/profile
+
+IFS=. read -r i1 i2 i3 i4 <<< "$BOOT2DOCKER_HOST_IP"
+IFS=. read -r m1 m2 m3 m4 <<< "$BOOT2DOCKER_NetworkMask"
+BOOT2DOCKER_Network=$(printf "%d.%d.%d.%d\n" "$((i1 & m1))" "$((i2 & m2))" "$((i3 & m3))" "$((i4 & m4))")
+unset IFS
 
 get_latest_release_name() {
     local LRN
@@ -38,6 +51,125 @@ download_latest() {
 
 log() {
     echo "[`date +"%Y-%m-%d %H:%M:%S"`] ${*}"
+}
+
+get_hostonlyif_name() {
+    DS=""
+    $VBM list hostonlyifs | while read LINE; do
+        if [ -z "$LINE" ]; then
+            if [[ $DS =~ (.*),.*,.*,$BOOT2DOCKER_HOST_IP,$BOOT2DOCKER_NetworkMask,.* ]]; then
+                IFNAME="${BASH_REMATCH[1]}"
+                if [[ "$IFNAME" == "$(get_dhcpserver_name $IFNAME)" ]]; then
+                    echo "$IFNAME"
+                    return 0
+                else
+                    log "Found interface \"$IFNAME\" with wrong DHCP Settings!"
+                    echo "$IFNAME" 
+                    return 1
+                fi
+            fi
+            DS=""
+        else
+            if [[ $LINE =~ .*:[[:space:]]+(.*) ]]; then
+                if [ -n "$DS" ]; then
+                    DS="$DS,"
+                fi
+                DS="$DS${BASH_REMATCH[1]}"
+            fi
+        fi
+    done
+}
+
+get_dhcpserver_name() {
+    IFNAME="$1"
+    DS=""
+    $VBM list dhcpservers | while read LINE; do
+        if [ -z "$LINE" ]; then
+            if [[ $DS =~ HostInterfaceNetworking-$IFNAME,$BOOT2DOCKER_DHCP_IP,$BOOT2DOCKER_NetworkMask,$BOOT2DOCKER_lowerIPAddress,$BOOT2DOCKER_upperIPAddress,$BOOT2DOCKER_DHCP_Enabled ]]; then
+                echo "$IFNAME"
+                break
+            fi
+            DS=""
+        else
+            if [[ $LINE =~ .*:[[:space:]]+(.*) ]]; then
+                if [ -n "$DS" ]; then
+                    DS="$DS,"
+                fi
+                DS="$DS${BASH_REMATCH[1]}"
+            fi
+        fi
+    done 
+}
+
+create_hostonlyif() {
+    IFNAME=$(get_hostonlyif_name)
+    IFNAME_ERROR=$?
+    if [[ "$IFNAME_ERROR" == "1" ]]; then # Wrong DHCP Setting
+        echo "Found interface \"$IFNAME\" with wrong DHCP settings!"
+        if ask "Would you like to reset it? (Y/N) " N ; then
+            $VBM dhcpserver modify \
+                --ifname $IFNAME \
+                --ip $BOOT2DOCKER_DHCP_IP \
+                --netmask $BOOT2DOCKER_NetworkMask \
+                --lowerip $BOOT2DOCKER_lowerIPAddress \
+                --upperip $BOOT2DOCKER_upperIPAddress \
+                --enable
+        else
+            log "Failed to update host only interface with DHCP settings!"
+            exit 1
+        fi
+    fi
+    if [[ -z "$IFNAME" ]]; then
+        OUTPUT=$($VBM hostonlyif create)
+        if [[ $OUTPUT =~ Interface[[:space:]]\'(.*)\'.* ]]; then
+            IFNAME="${BASH_REMATCH[1]}"
+            $VBM hostonlyif ipconfig $IFNAME \
+                --ip $BOOT2DOCKER_HOST_IP \
+                --netmask $BOOT2DOCKER_NetworkMask
+        else
+            log "Failed to create host only interface!"
+            exit 1
+        fi
+        $VBM dhcpserver add \
+            --ifname $IFNAME \
+            --ip $BOOT2DOCKER_DHCP_IP \
+            --netmask $BOOT2DOCKER_NetworkMask \
+            --lowerip $BOOT2DOCKER_lowerIPAddress \
+            --upperip $BOOT2DOCKER_upperIPAddress \
+            --enable
+    fi
+    echo "$IFNAME"
+}
+
+ask() {
+    while true; do
+ 
+        if [ "${2:-}" = "Y" ]; then
+            prompt="Y/n"
+            default=Y
+        elif [ "${2:-}" = "N" ]; then
+            prompt="y/N"
+            default=N
+        else
+            prompt="y/n"
+            default=
+        fi
+ 
+        # Ask the question
+        read -p "$1 [$prompt] " REPLY
+ 
+        # Default?
+        if [ -z "$REPLY" ]; then
+            REPLY=$default
+        fi
+ 
+        # Check if the reply is valid
+        case "$REPLY" in
+            Y*|y*) return 0 ;;
+            N*|n*) return 1 ;;
+        esac
+ 
+    done
 }
 
 init() {
@@ -109,21 +241,15 @@ init() {
 	    $VBM modifyvm $VM_NAME \
         	--natpf1 delete "docker"
     fi
+    IFNAME2=$(create_hostonlyif)
     $VBM modifyvm $VM_NAME \
         --nic2 hostonly \
-        --hostonlyadapter2 vboxnet0 \
+        --hostonlyadapter2 $IFNAME2 \
         --nictype2 $VM_NIC \
         --cableconnected2 on
     $VBM modifyvm $VM_NAME \
         --natpf1 "ssh,tcp,127.0.0.1,$SSH_HOST_PORT,,22" \
         --natpf1 "docker,tcp,127.0.0.1,$DOCKER_PORT,,4243"
-
-    # CFWPORTS=""
-    # for port in {49000..49900}
-    #     do
-    #         CFWPORTS="$CFWPORTS --natpf1 zfp$port,tcp,127.0.0.1,$port,,$port"
-    #     done
-    # $VBM modifyvm $VM_NAME $CFWPORTS
 
     if [ ! -e $BOOT2DOCKER_ISO ]; then
         log "boot2docker.iso not found."
@@ -366,7 +492,7 @@ docker_cmd() {
         log "nfs /etc/exports add $MHD_HD_SHARE"
 
         SHARE_ESCAPED="${MHD_HD_SHARE//\//\/}"
-        MHD_HD_EXPORT_CMD="sudo sed -i.bak '/\"$SHARE_ESCAPED\"/d' /etc/exports; sudo echo \"\\\"$MHD_HD_SHARE\\\" -network 192.168.56.0 -mask 255.255.255.0 -alldirs -mapall=$MUID:$MGID\" >> /etc/exports; sudo nfsd update"
+        MHD_HD_EXPORT_CMD="sudo sed -i.bak '/\"$SHARE_ESCAPED\"/d' /etc/exports; sudo echo \"\\\"$MHD_HD_SHARE\\\" -network $BOOT2DOCKER_Network -mask $BOOT2DOCKER_NetworkMask -alldirs -mapall=$MUID:$MGID\" >> /etc/exports; sudo nfsd update"
         unamestr=`uname`
 
         if [[ ! `sudo -v` ]] && [[ "$unamestr" == "Darwin" ]]; then
@@ -379,7 +505,7 @@ docker_cmd() {
         fi
         log "mount $MHD_HD_SHARE to $MHD_HD_MOUNT"
         # sudo /bin/bash -c echo "\"$MHD_HD_SHARE\" -network 192.168.56.0 -mask 255.255.255.0 -alldirs -mapall=502:20" >> /etc/exports
-        do_ssh "sudo mkdir -p $MHD_HD_MOUNT; sudo /usr/local/etc/init.d/nfs-client start; sudo mount 192.168.56.1:$MHD_HD_SHARE $MHD_HD_MOUNT"
+        do_ssh "sudo mkdir -p $MHD_HD_MOUNT; sudo /usr/local/etc/init.d/nfs-client start; sudo mount $BOOT2DOCKER_HOST_IP:$MHD_HD_SHARE $MHD_HD_MOUNT"
         DCMD="${DCMD/$MHD_ORIG/$MHD_OPTION}"
     fi
 
